name: TypeScript Container Action Template
description: Template to create a GitHub container action in Node.js with TypeScript
author: kevinpollet <pollet.kevin@gmail.com>
branding:
  icon: book-open
  color: blue
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  message:
    description: "Message displayed in pr comment"
    required: true
runs:
  using: docker
  image: Dockerfile
